### ISSUE TITLE
Does not work with CRM 2016sp1 (8.1.0.359)

### ISSUE THREAD

**Issue by Roel3824** [BESDev/Celedon-Autonumber-RTM#3] opened 2017-04-21 15:07 UTC
I tested this with CRM2015 update 0.2 and it works fine. With CRM2016 sp1 however the numbers are not generated and when creating an autonumbering record the name of the record is not auto created as it is in CRM2015.
Hope you will fix this because it is a very good solution.
Roel

**Comment by Dremor** [comment] 2017-07-10 14:31
As the original developers don't seem to respond, I forked the repository (on Gitlab, link asap), and started to work a cleanup of the codebase.
I have already found some issues that may be the cause of this problem, but I don't have yet a CRM 2016 instance to test if it works.

**Comment by travis-sharp** [comment] 2017-07-10 19:06
@Roel3824 Thank-you for your bug report. We will look into the issue.

**Comment by Roel3824** [comment] 2017-07-11 19:41
@Dremor, thanks! It seems that your comment also woke up the original developers. For now I have already found another autonumbering solution on Codeplex that works fine as well. This one however is superior if it works. I am willing to test on my own Dynamics CRM 2016/365 online test instance if it helps you.

**Comment by Dremor** [comment] 2017-07-13 12:35
@Roel3824 : this isn't the developer. The only contributor is @wedge905: https://github.com/BESDev/Celedon-Autonumber-RTM/graphs/contributors

**Comment by Dremor** [comment] 2017-07-17 15:50
@Roel3824 : Giving a "kick in the anthill" sometime works ;)

@tsharp : is @travis-sharp your alt-account? If so, sorry for doubting you.

**Comment by tsharp** [comment] 2017-07-17 16:21
@Dremor My alt is travis-sharp :)

**Comment by StephenDKing** [comment] 2017-07-17 17:59
I'm currently using it with an Onprem Dynamics 2016 pre-December update in prod and post December update in dev.

**Comment by fusionware** [comment] 2017-10-09 03:18
Was there a fix for this?  I'm currently using 1.1.1 in one solution and it works perfectly, but I've just started development of a new solution and it's failing to work.  As mentioned in a previous comment, when creating a new record the name of the record is not getting automatically set any more.

**Comment by tsharp** [comment] 2017-10-26 19:37
This issue is resolved with v1.2.0 of the Auto-Number solution.

**Closed by tsharp** 2017-10-26 19:37 UTC
Labels: bug
